name: skct_phone_dir
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  injectable: ^2.3.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  auto_route: ^7.8.4
  get_it: ^7.6.4
  provider: ^6.0.5
  google_sign_in: ^6.1.5
  dartz: ^0.10.1
  logger: ^2.0.2+1
  sizer: ^2.0.15
  flutter_animate: ^4.2.0+1
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  sliver_tools: ^0.2.12
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  change_app_package_name: ^1.1.0
  flutter_gen_runner: ^5.3.2
  freezed: ^2.4.5
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
