// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsUNETGjdrzkrgugyoBpUTXUFsnvZlQDs',
    appId: '1:751060442656:android:4035d24c6956184031a645',
    messagingSenderId: '751060442656',
    projectId: 'skct-dir',
    storageBucket: 'skct-dir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI3rIXVEZZd41GYrYgl243hc0YfhImhtE',
    appId: '1:751060442656:ios:9fc77fff630d938431a645',
    messagingSenderId: '751060442656',
    projectId: 'skct-dir',
    storageBucket: 'skct-dir.appspot.com',
    androidClientId: '751060442656-h608ouib3onghv2ji9p0j0d5i736jkqc.apps.googleusercontent.com',
    iosClientId: '751060442656-44emm2e6q0e0nrub6q0ftnt9mk7icmu0.apps.googleusercontent.com',
    iosBundleId: 'com.example.skctPhoneDir',
  );
}
